/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   julia.c                                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jchacon- <jchacon-@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/11/15 16:40:59 by julia             #+#    #+#             */
/*   Updated: 2025/11/16 15:24:27 by jchacon-         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "fractol.h"

/*
** Computes the color of a single pixel for the Julia set.
**
** For each pixel, we convert its (x, y) screen position into a complex
** number Z0. The Julia set is generated by repeatedly applying:
**
**        Z(n+1) = Z(n)^2 + C
**
** where C is a constant complex number chosen by the user.
**
** If |Z| grows beyond 2, the point escapes and its escape rate determines
** the pixel color. If it does not escape within the maximum iteration
** limit, the point is considered part of the Julia set and is colored as such.
*/

void	calculate_julia(t_fractal *fractal)
{
	int		i;
	double	tmp;
	double	zx;
	double	zy;

	zx = ((fractal->x - SIZE / 2.0) / fractal->zoom) + fractal->offset_x;
	zy = ((fractal->y - SIZE / 2.0) / fractal->zoom) + fractal->offset_y;
	i = 0;
	while (i < fractal->max_iterations)
	{
		tmp = zx;
		zx = zx * zx - zy * zy + fractal->cx;
		zy = 2 * zy * tmp + fractal->cy;
		if (zx * zx + zy * zy >= 4)
			break ;
		i++;
	}
	put_color_to_pixel(fractal, fractal->x, fractal->y, get_color(fractal, i));
}

// alternativa a blancos//grises
// 	if (i == fractal->max_iterations)
// 		put_color_to_pixel(fractal, fractal->x, fractal->y, 0xFFFFFF);
// 	else
// 	{
// 		double	t;
// 		int		shade;
// 		int		color;

// 		t = (double)i / fractal->max_iterations;
// 		shade = (int)(255 * (1.0 - t));
// 		color = (shade << 16) | (shade << 8) | shade;
// 		put_color_to_pixel(fractal, fractal->x, fractal->y, color);
// 	}
// }